### ISSUE TITLE
Why are we panicking instead of returning None?

### ISSUE THREAD

**Issue by JPMoresmau** [XAMPPRocky/Chelone#1]
Hello, I was trying to parse a Turtle document without setting the base URL, and I got a panic at:
```
  11: core::result::Result<url::Url, url::parser::ParseError>::unwrap<url::Url,url::parser::ParseError>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\result.rs:798
  12: chelone::Graph::parse_iriref
             at C:\Users\jean-philippem\.cargo\registry\src\github.com-1ecc6299db9ec823\chelone-0.1.3\src\lib.rs:485
```

We're in a function that returns Option<Iri>, why are we panicking instead of returning None? Isn't that why we return a Result when we create a Graph, to capture such errors?

Thanks for any clarification on usage!!

**Comment by XAMPPRocky** [comment]
@JPMoresmau Thank you for your issue! There is no intent behind the panicking behaviour. This crate is still pre 1.0, and of course I plan to remove all unintentional panics in the code. Right though you encounter these in the code as removing the panicking behaviour is not the current priority. I have made a commit to master that removes those unwraps. If you point your `Cargo.toml` to that then this specific unwrap should go away.

Feel free to file more issues if you encounter more panics. When you do, I would appreciate it if you also included the turtle document if possible and print the panic output with `RUST_BACKTRACE=1`. They would help me figure out if the reasons for panicking are legitimate or if they are due to internal errors.
